spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: root
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true